# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: ghuff_rony@yahoo.com
copyright_name: Gee/SoalUts/T.informatika
description: "Soal Pengantar Teknologi Informasi (PTI).Teknik Informatika Unila"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://1615061008.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

